development:
  adapter: mysql2
  username: root
  password: R2N0nen0ne
  encoding: utf8
  host: 127.0.0.1
  database: devise-test-dev
  
test: &test
  adapter: mysql2
  username: root
  password: R2N0nen0ne
  encoding: utf8
  host: 127.0.0.1
  database: devise-test-test
  
production:
  adapter: mysql2
  username: root
  password: R2N0nen0ne
  encoding: utf8
  host: 127.0.0.1
  database: devise-test
cucumber:
  <<: *test